# Generated by Django 4.2.7 on 2025-08-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=32)),
                ('parameter', models.CharField(max_length=32)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('value', models.FloatField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='weatherdata',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='parameter',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='region',
        ),
        migrations.DeleteModel(
            name='DataSource',
        ),
        migrations.DeleteModel(
            name='WeatherData',
        ),
        migrations.DeleteModel(
            name='WeatherParameter',
        ),
        migrations.DeleteModel(
            name='WeatherRegion',
        ),
    ]
