# Generated by Django 4.2.7 on 2025-08-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_weatherrecord_alter_weatherdata_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherrecord',
            name='season',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='weatherrecord',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
