# Generated by Django 4.2.7 on 2025-08-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_weatherrecord_season_alter_weatherrecord_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonalWeatherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=32)),
                ('parameter', models.CharField(max_length=32)),
                ('year', models.IntegerField()),
                ('season', models.CharField(max_length=8)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='weatherrecord',
            name='season',
        ),
    ]
