# Generated by Django 4.2.7 on 2025-08-14 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_seasonalweatherrecord_remove_weatherrecord_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seasonalweatherrecord',
            name='parameter',
        ),
        migrations.RemoveField(
            model_name='seasonalweatherrecord',
            name='region',
        ),
        migrations.RemoveField(
            model_name='seasonalweatherrecord',
            name='year',
        ),
        migrations.AddField(
            model_name='seasonalweatherrecord',
            name='weather_record',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_records', to='weather.weatherrecord'),
            preserve_default=False,
        ),
    ]
