# Generated by Django 4.2.7 on 2025-08-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_remove_seasonalweatherrecord_parameter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherrecord',
            name='parameter',
        ),
        migrations.RemoveField(
            model_name='weatherrecord',
            name='value',
        ),
        migrations.AddField(
            model_name='weatherrecord',
            name='Rainfall',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherrecord',
            name='Sunshine',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherrecord',
            name='Tmax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherrecord',
            name='Tmean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherrecord',
            name='Tmin',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
