name: Django CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  PYTHON_VERSION: '3.11'
  DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db

jobs:
  test:
    name: Test with PostgreSQL
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-django pytest-cov
    
    - name: Create static files directory
      run: mkdir -p static
      
    - name: Run tests with Django test runner
      env:
        DATABASE_URL: ${{ env.DATABASE_URL }}
        SECRET_KEY: test-secret-key
        DEBUG: 'True'
        STATIC_ROOT: ${{ github.workspace }}/staticfiles
        STATICFILES_DIRS: ${{ github.workspace }}/static
      run: |
        python manage.py test --noinput
        pytest --cov=.

  deploy:
    name: Deploy to production
    needs: test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: 'just-a-placeholder'
    
    - name: Deploy to server
      run: |
        # Add your deployment commands here
        # Example:
        # rsync -avz --delete . user@your-server:/path/to/app
        echo "Deployment would happen here"
